### ISSUE TITLE
Doesn't work on Java 9+

### ISSUE THREAD

**Issue by fgabolde** [redskap/swagger-brake-maven-plugin#15]
We are using Java 11 for a project that packages an OpenAPI 3 spec (btw, does this project support v3?). The plugin doesn't seem to work with the changes in Java 9, where the Java EE modules were removed from the core JDK.

```
[INFO] Downloading latest artifact from repository '<snip>' with groupId '<snip>' artifactId '<snip>'
[info] Latest version of the artifact could not be retrieved from <snip> with <snip>:<snip>
[info] Assuming this is the first version of the artifact, skipping check for breaking changes

io.redskap.swagger.brake.runner.exception.LatestArtifactDownloadException: Error while downloading the latest version of the artifact
	at io.redskap.swagger.brake.runner.download.ArtifactDownloaderHandler.handle(ArtifactDownloaderHandler.java:43)
	at io.redskap.swagger.brake.runner.Runner.run(Runner.java:27)
	at io.redskap.swagger.brake.runner.Starter.start(Starter.java:15)
	at io.redskap.swagger.brake.maven.StarterWrapper.start(StarterWrapper.java:11)
	at io.redskap.swagger.brake.maven.Executor.execute(Executor.java:22)
	at io.redskap.swagger.brake.maven.SwaggerBrakeMojo.execute(SwaggerBrakeMojo.java:55)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:956)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:192)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.lang.RuntimeException: Cannot get metadata
	at io.redskap.swagger.brake.maven.maven2.MavenMetadataDownloader.download(MavenMetadataDownloader.java:29)
	at io.redskap.swagger.brake.maven.maven2.LatestArtifactVersionResolver.resolve(LatestArtifactVersionResolver.java:18)
	at io.redskap.swagger.brake.maven.maven2.Maven2LatestArtifactDownloader.download(Maven2LatestArtifactDownloader.java:19)
	at io.redskap.swagger.brake.runner.download.ArtifactDownloaderHandler.handle(ArtifactDownloaderHandler.java:36)
	... 27 more
Caused by: javax.xml.bind.JAXBException: Implementation of JAXB-API has not been found on module path or classpath.
 - with linked exception:
[java.lang.ClassNotFoundException: com.sun.xml.internal.bind.v2.ContextFactory]
	at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:278)
	at javax.xml.bind.ContextFinder.find(ContextFinder.java:421)
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:721)
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:662)
	at io.redskap.swagger.brake.maven.maven2.MavenMetadataDownloader.getMetadata(MavenMetadataDownloader.java:35)
	at io.redskap.swagger.brake.maven.maven2.MavenMetadataDownloader.download(MavenMetadataDownloader.java:27)
	... 30 more
Caused by: java.lang.ClassNotFoundException: com.sun.xml.internal.bind.v2.ContextFactory
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
	at javax.xml.bind.ServiceLoaderUtil.nullSafeLoadClass(ServiceLoaderUtil.java:122)
	at javax.xml.bind.ServiceLoaderUtil.safeLoadClass(ServiceLoaderUtil.java:155)
	at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:276)
	... 35 more
```

**Comment by galovics** [comment]
Hi @fgabolde. 

- Does this project support v3? -> it does not prohibit using a V3 schema. Some of the V3 features are supported.
- On the JavaEE modules with Java9+ - it was a known issue and is already fixed in the upcoming 2.0.0 release (planned for EOW)

Let me know if you have further questions.
